import "./globals.css";

export const metadata = {
  title:
    "LLMs platform for automating mundane back-end tasks efficiently - Unpod.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
